/**
 * ANFSF Pipeline — Code Annotation Engine
 *
 * Analyzes git diffs to classify each code block as:
 *   - generated: untouched skeleton code from ANFSF
 *   - modified: developer-edited code
 *   - new: developer-created code
 *
 * Used in Stage 2 (development) to track code provenance.
 * Annotation data feeds Stage 5 (archival → component extraction).
 *
 * Task: T-202
 */

import type { GiteaDiff, GiteaCommit, GiteaClient as GiteaClientType } from '../integrations/gitea-client';

// ============================================================================
// Types
// ============================================================================

export type CodeSource = 'generated' | 'modified' | 'new';

export interface CodeAnnotation {
  file: string;
  startLine: number;
  endLine: number;
  source: CodeSource;
  commitSha: string;
  annotatedAt: number;
}

export interface AnnotationResult {
  projectId: string;
  commitSha: string;
  annotations: CodeAnnotation[];
  summary: {
    totalFiles: number;
    generatedFiles: number;
    modifiedFiles: number;
    newFiles: number;
    generatedLines: number;
    modifiedLines: number;
    newLines: number;
  };
}

// ============================================================================
// Annotation Engine
// ============================================================================

export class CodeAnnotator {
  /**
   * The initial set of file paths generated by ANFSF.
   * Any file NOT in this set is classified as 'new'.
   */
  private generatedFiles: Set<string>;

  constructor(generatedFilePaths: string[]) {
    this.generatedFiles = new Set(generatedFilePaths);
  }

  /**
   * Analyze a commit's diff and produce annotations.
   *
   * @param commit - The commit metadata
   * @param diffs - Per-file diffs from Gitea
   * @param projectId - The ANFSF project ID
   */
  annotate(
    commit: GiteaCommit,
    diffs: GiteaDiff[],
    projectId: string,
  ): AnnotationResult {
    const annotations: CodeAnnotation[] = [];
    let generatedFiles = 0;
    let modifiedFiles = 0;
    let newFiles = 0;
    let generatedLines = 0;
    let modifiedLines = 0;
    let newLines = 0;

    for (const diff of diffs) {
      const source = this.classifyFile(diff.filename, diff.status);

      // Count files
      switch (source) {
        case 'generated': generatedFiles++; break;
        case 'modified': modifiedFiles++; break;
        case 'new': newFiles++; break;
      }

      // Count lines from patch
      const lines = this.countLines(diff);

      // Create annotation (with or without patch data)
      annotations.push({
        file: diff.filename,
        startLine: 0,
        endLine: lines > 0 ? lines : (diff.additions + diff.deletions),
        source,
        commitSha: commit.sha,
        annotatedAt: Date.now(),
      });

      switch (source) {
        case 'generated': generatedLines += lines; break;
        case 'modified': modifiedLines += lines; break;
        case 'new': newLines += lines; break;
      }
    }

    return {
      projectId,
      commitSha: commit.sha,
      annotations,
      summary: {
        totalFiles: diffs.length,
        generatedFiles,
        modifiedFiles,
        newFiles,
        generatedLines,
        modifiedLines,
        newLines,
      },
    };
  }

  // ==========================================================================
  // Classification
  // ==========================================================================

  /**
   * Classify a file based on filename and diff status.
   */
  private classifyFile(filename: string, status: GiteaDiff['status']): CodeSource {
    const isGenerated = this.generatedFiles.has(filename);

    if (status === 'added' && !isGenerated) {
      return 'new';
    }

    if (isGenerated && (status === 'modified' || status === 'renamed')) {
      return 'modified';
    }

    if (isGenerated && status === 'added') {
      return 'generated';
    }

    if (isGenerated && status === 'removed') {
      return 'modified'; // Developer intentionally removed skeleton code
    }

    // Default: if file was in generated set, it's generated; otherwise new
    return isGenerated ? 'generated' : 'new';
  }

  /**
   * Count lines affected by a diff.
   */
  private countLines(diff: GiteaDiff): number {
    if (diff.additions !== undefined && diff.deletions !== undefined) {
      return diff.additions + diff.deletions;
    }
    // Fallback: count patch lines
    if (diff.patch) {
      return diff.patch.split('\n').length;
    }
    return 0;
  }

  /**
   * Add files to the generated file set (e.g., after a skeleton re-generation).
   */
  addGeneratedFiles(paths: string[]): void {
    for (const p of paths) {
      this.generatedFiles.add(p);
    }
  }

  /**
   * Get the current set of known generated files.
   */
  getGeneratedFiles(): string[] {
    return [...this.generatedFiles];
  }
}
