/**
 * ANFSF Pipeline — Task Package Generator (T-206)
 *
 * After skeleton generation, produces TASK.md files for frontend and backend
 * developers. Each task includes file paths, line ranges, dependencies, and priority.
 */

import type { GeneratedCode, GeneratedFile } from '../agents/code-generation-loop';

// ============================================================================
// Types
// ============================================================================

export interface DevTask {
  id: string;
  title: string;
  description: string;
  files: string[];
  dependencies: string[];
  priority: 'P0' | 'P1' | 'P2' | 'P3';
  estimatedHours: number;
}

export interface TaskPackage {
  frontend: {
    tasks: DevTask[];
    summary: { total: number; p0: number; p1: number; estimatedHours: number };
  };
  backend: {
    tasks: DevTask[];
    summary: { total: number; p0: number; p1: number; estimatedHours: number };
  };
}

// ============================================================================
// Generator
// ============================================================================

export class TaskGenerator {
  /**
   * Generate a task package from the skeleton code's file list.
   *
   * Heuristic: files under src/pages/ or src/components/ → frontend
   *            files under src/routes/ or src/services/ → backend
   *            files named TASK.md → skipped (these are output)
   */
  generate(code: GeneratedCode): TaskPackage {
    const frontendFiles = code.files.filter(f =>
      f.path.includes('pages/') || f.path.includes('components/') ||
      f.path.includes('App.tsx') || f.path.includes('index.tsx') ||
      f.path.includes('package.json') && !f.path.includes('server'),
    );

    const backendFiles = code.files.filter(f =>
      f.path.includes('routes/') || f.path.includes('services/') ||
      f.path.includes('server') || f.path.includes('schema') ||
      f.path.includes('database'),
    );

    const frontendTasks = this.buildTasks('fe', frontendFiles);
    const backendTasks = this.buildTasks('be', backendFiles);

    return {
      frontend: {
        tasks: frontendTasks,
        summary: this.summarize(frontendTasks),
      },
      backend: {
        tasks: backendTasks,
        summary: this.summarize(backendTasks),
      },
    };
  }

  /**
   * Build a Markdown TASK.md from a set of development tasks.
   */
  toMarkdown(pkg: TaskPackage): { frontend: string; backend: string } {
    return {
      frontend: this.renderMarkdown('Frontend', pkg.frontend.tasks, pkg.frontend.summary),
      backend: this.renderMarkdown('Backend', pkg.backend.tasks, pkg.backend.summary),
    };
  }

  // ==========================================================================
  // Private
  // ==========================================================================

  private buildTasks(prefix: string, files: GeneratedFile[]): DevTask[] {
    const tasks: DevTask[] = [];
    let taskIndex = 1;

    for (const file of files) {
      if (file.path === 'TASK.md') continue;

      tasks.push({
        id: `${prefix}-${String(taskIndex).padStart(3, '0')}`,
        title: `Implement ${file.path}`,
        description: `Open \`${file.path}\` and implement the business logic. Look for \`// TODO:\` comments marking where code is needed.`,
        files: [file.path],
        dependencies: [],
        priority: taskIndex <= 3 ? 'P0' : 'P1' as 'P0' | 'P1',
        estimatedHours: this.estimateHours(file),
      });
      taskIndex++;
    }

    return this.sortByPriority(tasks);
  }

  private estimateHours(file: GeneratedFile): number {
    const content = file.content || '';
    const todoCount = (content.match(/\/\/\s*TODO/g) || []).length;
    if (todoCount >= 5) return 4;
    if (todoCount >= 2) return 2;
    return 1;
  }

  private sortByPriority(tasks: DevTask[]): DevTask[] {
    const order = { P0: 0, P1: 1, P2: 2, P3: 3 };
    return tasks.sort((a, b) => order[a.priority] - order[b.priority]);
  }

  private summarize(tasks: DevTask[]): TaskPackage['frontend']['summary'] {
    return {
      total: tasks.length,
      p0: tasks.filter(t => t.priority === 'P0').length,
      p1: tasks.filter(t => t.priority === 'P1').length,
      estimatedHours: tasks.reduce((sum, t) => sum + t.estimatedHours, 0),
    };
  }

  private renderMarkdown(
    role: string,
    tasks: DevTask[],
    summary: TaskPackage['frontend']['summary'],
  ): string {
    const lines: string[] = [
      `# ${role} Development Tasks`,
      `> Generated by ANFSF. ${summary.total} tasks, estimated ${summary.estimatedHours}h.`,
      '',
      '## Summary',
      `- Total tasks: ${summary.total}`,
      `- P0 (must do): ${summary.p0}`,
      `- P1 (should do): ${summary.p1}`,
      `- Estimated hours: ${summary.estimatedHours}`,
      '',
      '## Tasks',
      '',
    ];

    for (const task of tasks) {
      lines.push(`### ${task.id}: ${task.title}`);
      lines.push(`- **Priority**: ${task.priority}`);
      lines.push(`- **Estimate**: ${task.estimatedHours}h`);
      lines.push(`- **Files**: ${task.files.join(', ')}`);
      lines.push(`- **Dependencies**: ${task.dependencies.length > 0 ? task.dependencies.join(', ') : 'None'}`);
      lines.push(`- **Description**: ${task.description}`);
      lines.push('');
    }

    return lines.join('\n');
  }
}
