/**
 * ANFSF — Tool System Type Definitions
 *
 * Core interfaces for the LLM-facing tool system.
 * Separate from VerificationTool — these are tools the LLM can invoke
 * during generation/fix, not post-hoc verification plugins.
 *
 * Phase 2: Tool System Infrastructure
 */

// ============================================================================
// Tool Definition Types (LLM-facing schema)
// ============================================================================

/**
 * Parameter definition for a tool — maps to OpenAI/DashScope function calling
 * parameter schema.
 */
export interface ToolParameter {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'array' | 'object';
  description: string;
  required: boolean;
  default?: unknown;
  /** For enum-like parameters */
  enum?: string[];
  /** For array types, the schema of array items */
  items?: ToolParameter;
  /** For object types, nested properties */
  properties?: Record<string, ToolParameter>;
}

/**
 * Tool definition sent to the LLM as part of the function-calling schema.
 */
export interface ToolDefinition {
  /** Unique tool name (e.g. "read_file", "write_file", "execute_bash") */
  name: string;
  /** Human-readable description for the LLM to decide when to use */
  description: string;
  /** Parameters the LLM must provide */
  parameters: ToolParameter[];
  /** Execution mode */
  mode: 'readonly' | 'readwrite';
  /** Whether this tool needs sandbox isolation */
  requiresSandbox: boolean;
}

// ============================================================================
// Tool Call / Result Types (runtime)
// ============================================================================

/**
 * A tool call made by the LLM — maps to OpenAI tool_calls[].function.
 */
export interface ToolCall {
  /** Unique call ID (generated by LLM) */
  id: string;
  /** Name of the tool to invoke */
  name: string;
  /** Arguments provided by the LLM */
  arguments: Record<string, unknown>;
}

/**
 * Result of executing a tool call.
 */
export interface ToolResult {
  /** Matches the originating ToolCall.id */
  callId: string;
  /** Tool name for traceability */
  toolName: string;
  /** Whether execution succeeded */
  success: boolean;
  /** Output content (for reading tools) or status message */
  output: string;
  /** Error message if success is false */
  error?: string;
  /** Execution duration in ms */
  durationMs: number;
}

// ============================================================================
// Tool Interface (implemented by each tool)
// ============================================================================

/**
 * Context provided to tools at execution time.
 */
export interface ToolContext {
  /** Working directory for path-relative operations */
  workingDir: string;
  /** Optional sandbox executor for bash/exec tools */
  sandbox?: any; // SandboxExecutor — imported lazily to avoid circular deps
  /** Allowed paths (for read/write path validation) */
  allowedPaths?: string[];
  /** Timeout for tool execution in ms (default: 30s) */
  timeoutMs?: number;
}

/**
 * The Tool interface. Each tool has a static definition and an async
 * execute method. Implementations should be stateless.
 */
export interface Tool {
  /** Immutable tool metadata */
  readonly definition: ToolDefinition;

  /**
   * Execute the tool with the given parameters and context.
   * Should throw only for programming errors — runtime errors
   * should be returned as ToolResult.success === false.
   */
  execute(params: Record<string, unknown>, context: ToolContext): Promise<ToolResult>;
}

// ============================================================================
// Tool Execution Result Envelope
// ============================================================================

/**
 * Aggregated result from a multi-tool execution round.
 */
export interface ToolExecutionReport {
  /** Total number of tool calls in this round */
  totalCalls: number;
  /** Successful calls */
  succeeded: number;
  /** Failed calls */
  failed: number;
  /** Individual results */
  results: ToolResult[];
  /** Total wall-clock time for all executions */
  totalDurationMs: number;
}
